# Generated by Django 5.0.2 on 2024-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
