# Generated by Django 5.0.6 on 2024-05-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0005_alter_customuser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.BooleanField(choices=[(True, 'Student'), (False, 'Teacher')], default=False),
        ),
    ]
